AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy python lambda

Parameters:
  Revision:
    Type: String
    Description: The commit that originated this deployment. Helps trigger new deploys to the lambda.

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}"
      Handler: src.lambda_function.handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Code:
        S3Bucket: email-worker-bucket
        S3Key: !Sub "${Revision}.zip"
      Environment:
        Variables:
          QUEUE_URL: !ImportValue "email-worker-sqs-url-export"
      Runtime: python3.10
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref LambdaLayer

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaBasicExecution"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: '*'

  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-${Revision}"
      CompatibleRuntimes:
        - python3.10
      Content:
        S3Bucket: email-sender-service-bucket
        S3Key: dependencies.zip

  MyLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      EventSourceArn: !ImportValue "email-worker-sqs-arn-export"
      FunctionName: !GetAtt MyLambdaFunction.Arn
      Enabled: True

Outputs:
  LambdaName:
    Description: Name of the lambda
    Value: !Ref MyLambdaFunction
    Export:
      Name: !Sub "${AWS::StackName}-export"