AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation for creating a worker to be deployed to a specific cluster.

Resources:
  SQSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub ${AWS::StackName}
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}"

Outputs:
  QueueUrl:
    Description: Url of the queue
    Value: !Ref SQSQueue
    Export:
      Name: !Sub "${AWS::StackName}-url-export"
  QueueName:
    Description: Name of the queue
    Value: !GetAtt SQSQueue.QueueName
    Export:
      Name: !Sub "${AWS::StackName}-name-export"